spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/db/muzinut
    username: sa
    password: 12
    driver-class-name: org.h2.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: wontube100@gmail.com
    password: vcrrzrvvplnzpmxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000 #클라이언트가 SMTP 서버와의 연결을 설정하는 시간
          timeout: 5000 #클라이언트가 SMTP 서버로부터 응답을 대기하는 시간
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 이메일 인증 코드의 만료 시간 (30 * 60 * 1000 == 30분)
  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션이 뜰때 기존에 있던 데이터를 모두 삭제함
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace