spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/db/muzinut
    username: sa
    password: 12
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  file:
    dir: C:/Users/wndud/study/muzinut/file/

  mail:
    host: smtp.naver.com
    port: 465
    username: muzinut@naver.com
    password: 3whabwlsjt!@
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션이 뜰때 기존에 있던 데이터를 모두 삭제함
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace